### ISSUE TITLE
UI bugging me

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#227] opened 2019-02-25 11:37 UTC
https://drive.google.com/file/d/19GCYckTXpo6h898e6UbGDkxyz9MDSnLv/view

**Comment by samijuhani** [comment] 2019-02-25 11:59
Happens only with smaller screen on laptop. External screen not so bad.

**Comment by danieldunderfelt** [comment] 2019-02-26 04:25
I can't reproduce this. Which browser (exact version) and screen resolution are you using?

**Comment by samijuhani** [comment] 2019-02-26 06:33
Chrome Windows Versio 72.0.3626.109 (Virallinen koontiversio) (64-bittinen)

**Comment by samijuhani** [comment] 2019-02-26 06:34
1920x1080, 125% scaling

**Comment by samijuhani** [comment] 2019-02-26 06:35
And can't reproduce now but other small clitches visible

**Comment by samijuhani** [comment] 2019-02-26 06:36
Pretty sure these happend after taking computer out of dock and external displays.

**Comment by danieldunderfelt** [comment] 2019-02-26 06:45
I managed to reproduce it! The UI bugs out when I have a stop selected, and only on the newest versions of Chrome. I'll get it fixed!

**Comment by danieldunderfelt** [comment] 2019-02-26 06:48
Actually, it also happens when a stop is not selected, but you have to view the block list or the stop timetable list to trigger the bug. The route journeys list works fine. This gives me enough clues to track down the bug.

**Comment by samijuhani** [comment] 2019-02-26 06:50
Good!

**Comment by danieldunderfelt** [comment] 2019-02-26 07:53
Fixed in #228.

**Closed** 2019-02-26 08:02 UTC
Labels: bug
