### ISSUE TITLE
Wrong daytype 2.11.

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#473] opened 2019-11-04 09:49 UTC
Should not be sunday timetables 2.11.

"Jostain syystä Reittiloki näyttää pyhäinpäivälle la 2.11. sunnuntailähdöt, vaikka oli normaali lauantailiikenne, eli kaikkia yölähtöjä ei pääse nyt tarkistamaan.
Missähän su-liikenne tuo on määritelty? Joreen ei ole määritelty korvaavaa päivätyyppiä, jolloin oletuksena pitäisi olla kalenteripäivän (lauantai) mukainen liikenne. Jore ei siis tiedä, että tietty päivä onkin poikkeuksellisesti pyhäpäivä, joten tuo määrittely täytyy olla jossain muualla tehty. "

**Comment by danieldunderfelt** [comment] 2019-11-04 10:06
Our JORE is adamant that 2.11 uses Sunday timetables. The replacement day has been imported on 2019-08-26.

This is not a bug in the app. The replacement days will update if a new row with the same date is imported, but will of course not remove anything since this is a history database. All faulty entries are kept, but we can remove them manually if needed.

**Comment by danieldunderfelt** [comment] 2019-11-05 04:30
The issue seems to be that the exception day is scoped to a certain transport mode (in this case U routes) but applied to all departures due to the exception scope being very complicated to implement. I will try, but we also need to be alert about missing departures which can happen in edge cases that the query wasnt prepared for.

**Comment by danieldunderfelt** [comment] 2019-11-05 11:27
Fixed now. The departures are filtered according to scope. In cases where we have the routeId prior to querying for departures (eg. departures for a specific route or journey), we can find out the correct departure day types to query for before running the query. In other cases (eg. stop departures with many different routes) we need to query for all day types regardless of scope and filter afterwards. Neither solution resulted in noticeably longer loading times but did increase complexity somewhat.

**Closed** 2019-11-14 06:33 UTC
Labels: enhancement
