### ISSUE TITLE
Missing cancelled journey from Reittiloki

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#486] opened 2019-11-21 07:20 UTC
9643/1 7:15 19.11.2019 was cancelled 8:06:44 (after planned end of the journey). No remark of that in Reittiloki. Must be sink/db thing?

Expected: Should be marked as canceled.

https://reittiloki.hsl.fi/journey/20191119/071500/9643/1/0018_829?date=2019-11-19&mapView=60.21707430752684%2C24.95698928833008&route.routeId=9643&route.direction=1&route.originStopId=1111117&tab=&details-tab=journey-events&mapZoom=15&live=false&time=07%3A15%3A00&vehicle=0018%2F829

**Comment by danieldunderfelt** [comment] 2019-11-21 08:07
This departure is cancelled in dev, and I've confirmed that the cancellation exists in the dev database. It seems to be missing from stage and prod. If it would exist, Reittiloki would show the departure as cancelled as expected.

![Screenshot from 2019-11-21 10-07-06](https://user-images.githubusercontent.com/3145668/69318865-b872d980-0c46-11ea-9aea-18f739b487f8.png)

**Comment by samijuhani** [comment] 2019-11-21 08:20
Stage is also missing this. @AkiValiaho @hellej check why, what is dofferent between dev/prod

**Comment by hellej** [comment] 2019-12-11 12:05
@samijuhani All cancellations created or modified after 10.9. are now in the timescale db:s of all three envs, including this one. However, it doesn't yet appear in the UI assumably due to cache @danieldunderfelt (?) - we can close this if that is the case.

**Closed** 2019-12-11 12:21 UTC
Labels: bug
